"""Optimized VAD parameter presets.

These presets were generated by Bayesian optimization (Optuna TPE sampler)
using benchmark corpora:
- Japanese (JA): JSUT basic5000 subset
- English (EN): LibriSpeech test-clean subset

Optimization was performed with parakeet_ja (JA) and parakeet (EN) ASR engines.
See Issue #126 for detailed optimization results.

Usage:
    from livecap_cli.vad.presets import get_optimized_preset, VAD_OPTIMIZED_PRESETS
    from livecap_cli.vad import VADConfig

    # Get preset for specific VAD and language
    preset = get_optimized_preset("silero", "ja")
    if preset:
        vad_config = VADConfig.from_dict(preset["vad_config"])

    # Check available presets
    print(list(VAD_OPTIMIZED_PRESETS.keys()))  # ['silero', 'tenvad', 'webrtc']
"""

from __future__ import annotations

from typing import Any

# Optimization results from Phase D (Issue #126)
# Parameters from Phase D-2 (Bayesian optimization), scores from Phase D-4 (benchmark)
# Benchmark conditions: standard mode, parakeet_ja (JA) / parakeet (EN)
#
# Best VAD by language:
#   - JA: TenVAD (7.2% CER)
#   - EN: WebRTC (3.3% WER)
VAD_OPTIMIZED_PRESETS: dict[str, dict[str, dict[str, Any]]] = {
    # Silero VAD
    "silero": {
        "ja": {
            "vad_config": {
                "threshold": 0.294,
                "neg_threshold": 0.123,
                "min_speech_ms": 450,
                "min_silence_ms": 190,
                "speech_pad_ms": 150,
            },
            "metadata": {
                "score": 0.082,  # CER (Phase D-4 benchmark)
                "trials": 60,
            },
        },
        "en": {
            "vad_config": {
                "threshold": 0.252,
                "neg_threshold": 0.436,
                "min_speech_ms": 350,
                "min_silence_ms": 220,
                "speech_pad_ms": 130,
            },
            "metadata": {
                "score": 0.040,  # WER (Phase D-4 benchmark)
                "trials": 60,
            },
        },
    },
    # TenVAD - Best for Japanese
    "tenvad": {
        "ja": {
            "backend": {
                "hop_size": 256,
            },
            "vad_config": {
                "threshold": 0.204,
                "neg_threshold": 0.488,
                "min_speech_ms": 400,
                "min_silence_ms": 180,
                "speech_pad_ms": 90,
            },
            "metadata": {
                "score": 0.072,  # CER (Phase D-4 benchmark) - Best for JA
                "trials": 115,
            },
        },
        "en": {
            "backend": {
                "hop_size": 256,
            },
            "vad_config": {
                "threshold": 0.201,
                "neg_threshold": 0.206,
                "min_speech_ms": 300,
                "min_silence_ms": 240,
                "speech_pad_ms": 180,
            },
            "metadata": {
                "score": 0.034,  # WER (Phase D-4 benchmark)
                "trials": 60,
            },
        },
    },
    # WebRTC VAD - Best for English
    "webrtc": {
        "ja": {
            "backend": {
                "mode": 1,
                "frame_duration_ms": 30,
            },
            "vad_config": {
                # Note: threshold is not used for WebRTC (binary output)
                "min_speech_ms": 300,
                "min_silence_ms": 150,
                "speech_pad_ms": 80,
            },
            "metadata": {
                "score": 0.077,  # CER (Phase D-4 benchmark)
                "trials": 145,
            },
        },
        "en": {
            "backend": {
                "mode": 0,
                "frame_duration_ms": 30,
            },
            "vad_config": {
                "min_speech_ms": 450,
                "min_silence_ms": 280,
                "speech_pad_ms": 200,
            },
            "metadata": {
                "score": 0.033,  # WER (Phase D-4 benchmark) - Best for EN
                "trials": 60,
            },
        },
    },
}


def get_optimized_preset(
    vad_type: str,
    language: str,
) -> dict[str, Any] | None:
    """Get optimized preset for VAD type and language.

    Args:
        vad_type: VAD backend type ("silero", "tenvad", "webrtc")
        language: Language code ("ja", "en")

    Returns:
        Preset dictionary with "vad_config", optional "backend", and "metadata" keys.
        Returns None if no preset exists for the combination.

    Example:
        >>> preset = get_optimized_preset("silero", "ja")
        >>> preset["vad_config"]["threshold"]
        0.294
        >>> preset["metadata"]["score"]
        0.0647
    """
    return VAD_OPTIMIZED_PRESETS.get(vad_type, {}).get(language)


def get_available_presets() -> list[tuple[str, str]]:
    """Get list of available (vad_type, language) combinations.

    Returns:
        List of tuples (vad_type, language) for all available presets.

    Example:
        >>> get_available_presets()
        [('silero', 'ja'), ('silero', 'en'), ('tenvad', 'ja'), ...]
    """
    result = []
    for vad_type, languages in VAD_OPTIMIZED_PRESETS.items():
        for language in languages:
            result.append((vad_type, language))
    return result


def get_best_vad_for_language(language: str) -> tuple[str, dict[str, Any]] | None:
    """Get the best performing VAD preset for a language.

    Args:
        language: Language code ("ja", "en")

    Returns:
        Tuple of (vad_type, preset) for the best performing VAD.
        Returns None if no presets exist for the language.

    Example:
        >>> vad_type, preset = get_best_vad_for_language("ja")
        >>> vad_type
        'tenvad'
        >>> preset["metadata"]["score"]
        0.072
    """
    best_vad = None
    best_score = float("inf")

    for vad_type, languages in VAD_OPTIMIZED_PRESETS.items():
        if language in languages:
            preset = languages[language]
            score = preset["metadata"]["score"]
            if score < best_score:
                best_score = score
                best_vad = (vad_type, preset)

    return best_vad


__all__ = [
    "VAD_OPTIMIZED_PRESETS",
    "get_optimized_preset",
    "get_available_presets",
    "get_best_vad_for_language",
]
